spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: sivanandmishra24@gmail.com
    password: dkxc mujy lckb mhrp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
  servlet:
    context-path: /journal

logging:
  level:
    org.springframework.security: DEBUG

weather:
  api:
    key: b0a32bbcd48481a6fc5b92708a4edef7