spring:
  rabbitmq:
    addresses:
  data:
    redis:
      url: redis://default:qP1jnqpTp0sboQM4ApBmG2kjryzBw5Wb@laborer-cats-kitty-80185.db.redis.io:11626
    mongodb:
      uri: mongodb+srv://sivanandmishra24_db_user:sivanand24@cluster0.gnzgvyd.mongodb.net/journaldb?retryWrites=true&w=majority
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: sivanandmishra24@gmail.com
    password: dkxc mujy lckb mhrp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
  servlet:
    context-path: /journal

logging:
  level:
    org.springframework.security: DEBUG

weather:
  api:
    key: b0a32bbcd48481a6fc5b92708a4edef7