spring.data.mongodb.uri=mongodb+srv://sivanandmishra24_db_user:sivanand24@cluster0.gnzgvyd.mongodb.net/journaldb?retryWrites=true&w=majority
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references = true